export interface WeatherMetadata {
  modelrun_updatetime_utc: string;
  name: string;
  height: number;
  timezone_abbrevation: string;
  latitude: number;
  modelrun_utc: string;
  longitude: number;
  utc_timeoffset: number;
  generation_time_ms: number;
}

export interface WeatherUnits {
  relativehumidity: string;
  co: string;
  pollen_birch: string;
  predictability: string;
  precipitation: string;
  sunshinetime: string;
  aod550: string;
  time: string;
  pm10: string;
  airqualityindex: string;
  probability: string;
  cloudcover: string;
  no2: string;
  pm25: string;
  winddirection: string;
  ozone: string;
  windspeed: string;
  so2: string;
  visibility: string;
  pollen_olive: string;
  precipitation_probability: string;
  temperature: string;
  dust_concentration: string;
  pressure: string;
  pollen_grass: string;
}

export interface WeatherDataDay {
  time: string[];
  dust_concentration_max: (number | null)[];
  sealevelpressure_mean: number[];
  co_min: (number | null)[];
  airqualityindex_min: (number | null)[];
  dust_concentration_min: (number | null)[];
  sandstorm_alert: number[];
  temperature_instant: number[];
  convective_precipitation: number[];
  midclouds_mean: number[];
  totalcloudcover_min: number[];
  lowclouds_min: number[];
  lowclouds_mean: number[];
  midclouds_max: number[];
  temperature_mean: number[];
  predictability: number[];
  so2_mean: (number | null)[];
  pm25_max: (number | null)[];
  pollen_birch_mean: (number | null)[];
  uvindex: number[];
  precipitation_probability: number[];
  pollen_grass_min: (number | null)[];
  pollen_olive_max: (number | null)[];
  indexto1hvalues_start: number[];
  indexto1hvalues_end: number[];
  winddirection: number[];
  pollen_birch_max: (number | null)[];
  pm25_min: (number | null)[];
  sealevelpressure_min: number[];
  windspeed_min: number[];
  visibility_max: number[];
  visibility_mean: number[];
  windspeed_mean: number[];
  sunshine_time: number[];
  felttemperature_mean: number[];
  totalcloudcover_max: number[];
  windspeed_max: number[];
  relativehumidity_min: number[];
  pictocode: number[];
  so2_max: (number | null)[];
  pollen_grass_mean: (number | null)[];
  dust_concentration_mean: (number | null)[];
  relativehumidity_mean: number[];
  airqualityindex_max: (number | null)[];
  co_max: (number | null)[];
  precipitation_hours: number[];
  visibility_min: number[];
  airqualityindex_mean: (number | null)[];
  snowfraction: number[];
  highclouds_max: number[];
  predictability_class: number[];
  sealevelpressure_max: number[];
  humiditygreater90_hours: number[];
  aod550_mean: (number | null)[];
  felttemperature_max: number[];
  so2_min: (number | null)[];
  no2_max: (number | null)[];
  no2_min: (number | null)[];
  pollen_grass_max: (number | null)[];
  highclouds_mean: number[];
  pm25_mean: (number | null)[];
  rainspot: string[];
  lowclouds_max: number[];
  felttemperature_min: number[];
  precipitation: number[];
  no2_mean: (number | null)[];
  fog_probability: number[];
  ozone_max: (number | null)[];
  temperature_min: number[];
  relativehumidity_max: number[];
  midclouds_min: number[];
  pm10_mean: (number | null)[];
  aod550_max: (number | null)[];
  co_mean: (number | null)[];
  pm10_min: (number | null)[];
  pm10_max: (number | null)[];
  pollen_olive_min: (number | null)[];
  temperature_max: number[];
  ozone_mean: (number | null)[];
  aod550_min: (number | null)[];
  pollen_birch_min: (number | null)[];
  pollen_olive_mean: (number | null)[];
  totalcloudcover_mean: number[];
  ozone_min: (number | null)[];
  highclouds_min: number[];
}

export interface WeatherData1h {
  time: string[];
  snowfraction: number[];
  windspeed: number[];
  temperature: number[];
  precipitation_probability: number[];
  convective_precipitation: number[];
  rainspot: string[];
  pictocode: number[];
  felttemperature: number[];
  precipitation: number[];
  isdaylight: number[];
  uvindex: number[];
  relativehumidity: number[];
  sealevelpressure: number[];
  winddirection: number[];
  fog_probability: number[];
  sunshinetime: number[];
  highclouds: number[];
  lowclouds: number[];
  visibility: number[];
  midclouds: number[];
  totalcloudcover: number[];
}

export interface GetWeatherApiResponse {
  metadata: WeatherMetadata;
  units: WeatherUnits;
  data_day: WeatherDataDay;
  data_1h: WeatherData1h;
}
